backend:
  name: git-gateway
  repo: factn/resilienceapp_theme
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Home"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Hero, name: hero, widget: object, fields: [{label: Title, name: title, widget: string, required: true}, {label: Button, name: button, widget: list, fields: [{label: Label, name: label, widget: string, required: true}, {label: URL, name: url, widget: string, required: true}]}]}
          - {label: Mission, name: mission, widget: object, fields: [{label: Steps, name: step, widget: list, fields: [{label: Image, name: image, widget: image, required: true}, {label: Heading, name: heading, widget: string, required: true}]}]}
          - {label: Video, name: video, widget: object, fields: [{label: Title, name: title, widget: string, required: true}, {label: URL (Use embed URL), name: url, widget: string, required: true}]}
          - {label: Sections, name: section, widget: object, fields: [{label: Row, name: row, widget: list, fields: [{label: Image, name: image, widget: image, required: true}, {label: Heading, name: heading, widget: string, required: true}, {label: Text, name: text, widget: text, required: true}, {label: Button, name: button, widget: string, required: true}, {label: URL, name: url, widget: string, required: true}]}]}
          - {label: Contribute, name: contribute, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}, {label: Channel, name: channel, widget: list, fields: [{label: Image, name: image, widget: image, required: true}, {label: Heading, name: heading, widget: string}, {label: Text, name: text, widget: text}, {label: Button, name: button, widget: string, required: true}, {label: URL, name: url, widget: string, require: true}]}]}
          - {label: Team, name: team, widget: object, fields: [{label: Heading, name: heading, widget: string, required: true}, {label: Text, name: text, widget: text, required: true}, {label: Member, name: member, widget: list, fields: [{label: Image, name: image, widget: image, required: true}, {label: Heading, name: heading, widget: string, required: true}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/contribute/index.md"
        label: "Contribute"
        name: "contribute"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "form-demo"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/form-demo/index.md"
        label: "Form Demo"
        name: "formdemo"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "form-demo"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}